ok

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -326,52 +326,52 @@ jobs:
       - revert-migrations:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
+  # Run Smoke tests
   smoke-test:
     docker:
-      - image: python:3.7-alpine3.11 
+      - image: amazon/aws-cli
     steps:
       - checkout
+
       - run:
           name: Install dependencies
           command: |
-            apk add --update nodejs npm curl
-            apk add --update --no-cache python3 py3-pip
-            /usr/local/bin/python -m pip install --upgrade pip
-            pip install awscli
-            aws --version
+            yum install -y curl
+        
       - run:
-          name: Backend smoke test.
+          name: Get backend url And Run backend smoke tests
           command: |
-            export BACKEND_IP=$(
-              aws ec2 describe-instances \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --output text
-            )
-            echo "${BACKEND_IP}"
-            export API_URL="http://${BACKEND_IP}:3030" 
-            echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
+            # Fetch and prepare the BACKEND_IP env 
+            BACKEND_IP=$(aws --region us-east-1 \
+                ec2 describe-instances \
+                --filters \
+                "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                --query 'Reservations[*].Instances[*].[PublicIpAddress]' \
+                --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo $API_URL
+            if curl -s $API_URL/api/status | grep "ok"
             then
-                return 0
+              exit 0
             else
-                return 1
+              exit 1
             fi
       - run:
           name: Frontend smoke test.
           command: |
-              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-              if curl -s ${URL} | grep "Welcome"
-              then
-                return 0
-              else
-                return 1
-              fi
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-          
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
+            #Get Frontend URL and run frontend smoke tests
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              exit 1
+            else
+              exit 1
+            fi
+      #Destroy environment and revert migrations if job fails 
+      - destroy-environment
+      - revert-migrations
 
   # cloudfront-update:
   #   docker:
